### ISSUE TITLE
Prototype pollution ~vulnerability~

### ISSUE THREAD

**Issue by sno2** [ljharb/camelize#2]
Minimal reproduction:

```js
var camelize = require("camelize");

var json = {
  ____proto____: {
    isAdmin: true,
    toString: null,
  },
};

var response = camelize(json);

console.log(response); // {}

console.log(response.isAdmin); // true
console.log(response.toString()); // TypeError: response.toString is not a function
```

Disclosed responsibly because this was deemed as not a vulnerability by the maintainer on January 12, 2023 via Tidelift's email communications. I originally forgot about the issue last year, but after noticing that a prototype pollution vulnerability was found and reported with a CVE by the maintainer in [minimist](https://github.com/advisories/GHSA-xvch-5gv4-984h) I found the motivation to post publicly.

**Comment by ljharb** [comment]
Indeed, it’s not prototype pollution because that term describes polluting shared prototypes. Nobody cares if you hijack the prototype of an object you create.
